/*
* generated by Xtext
*/
package org.mybuild.myfile.ui.contentassist;

import org.mybuild.myfile.ui.contentassist.AbstractMyFileProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MyFileProposalProvider extends AbstractMyFileProposalProvider {

}
