/*
* generated by Xtext
*/
package org.embuild.emdsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class EmDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
