/*
* generated by Xtext
*/
package org.mybuild.configfile.ui.contentassist;

import org.mybuild.configfile.ui.contentassist.AbstractConfigFileProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ConfigFileProposalProvider extends AbstractConfigFileProposalProvider {

}
