#!/bin/sh

DATA_DIR=$(dirname $0)
ROOT_DIR=$DATA_DIR/../../../

DISK_IMG=./zrv-mandatory.img

if [ ! -f $DISK_IMG ]; then
	echo "No mandatory image found!" >&2
	echo "Download example one http://embox.googlecode.com/files/zrv-mandatory.img" >&2
	echo "and place it to current working directory" >&2
	exit 1
fi

$ROOT_DIR/scripts/qemu/auto_qemu -hda $DISK_IMG "$@"
