/*
 * generated by Xtext
 */
package org.mybuild.configfile;

import static com.google.inject.name.Names.named;

import org.eclipse.xtext.scoping.IScopeProvider;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.mybuild.configfile.scoping.ConfigFileImportedNamespaceAwareLocalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class ConfigFileRuntimeModule extends
		org.mybuild.configfile.AbstractConfigFileRuntimeModule {

	@Override
	public void configureIScopeProviderDelegate(com.google.inject.Binder binder) {
		binder.bind(IScopeProvider.class)
				.annotatedWith(
						named(AbstractDeclarativeScopeProvider.NAMED_DELEGATE))
				.to(ConfigFileImportedNamespaceAwareLocalScopeProvider.class);
	}

}
