/*
 * generated by Xtext
 */
package org.embuild.emdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EmDslUiModule extends org.embuild.emdsl.ui.AbstractEmDslUiModule {
	public EmDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
