#!/bin/bash

QEMU=qemu-system-i386
IMAGE=../../build/base/bin/embox
EMBOX_MODS_CONF=../../conf/mods.config
SMP=" "

grep "include embox.kernel.smp" $EMBOX_MODS_CONF > /dev/null
if [ $? -eq 0 ]; then
SMP="-smp 2,cores=2"
break
fi

echo "$SMP"

sudo $QEMU -kernel $IMAGE  $SMP \
 -net nic,model=e1000,macaddr=AA:BB:CC:DD:EE:12 \
 -net nic,model=e1000,macaddr=AA:BB:CC:DD:EE:22 \
 -net socket,mcast=230.0.0.1:12345 -nographic $@

