<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="myfile"
    nsURI="http://www.mybuild.org/MyFile" nsPrefix="MyFile">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" eType="#//Package"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" eSuperTypes="#//Named #//AnnotationTarget"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//AnnotationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//AnnotationTarget"
        eOpposite="#//AnnotationTarget/annotations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//PropertyValueBinding" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="singleValue" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnnotationTarget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//Annotation" containment="true" eOpposite="#//Annotation/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="self" eType="#//AnnotationTarget"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//Module"
        eOpposite="#//Module/subType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subType" upperBound="-1"
        eType="#//Module" eOpposite="#//Module/superType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allSuperType" upperBound="-1"
        eType="#//Module" changeable="false" volatile="true" transient="true" derived="true"
        eOpposite="#//Module/allSubType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allSubType" upperBound="-1"
        eType="#//Module" changeable="false" volatile="true" transient="true" derived="true"
        eOpposite="#//Module/allSuperType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//Member" containment="true" eOpposite="#//Member/containingModule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="depends" upperBound="-1"
        eType="#//Module" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependent" upperBound="-1"
        eType="#//Module" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provides" upperBound="-1"
        eType="#//Feature" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requires" upperBound="-1"
        eType="#//Feature" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sources" upperBound="-1"
        eType="#//FileName" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="#//FileName" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Member" eSuperTypes="#//AnnotationTarget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containingModule" eType="#//Module"
        eOpposite="#//Module/members"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependsMember" eSuperTypes="#//Member">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" unique="false"
        upperBound="-1" eType="#//Module"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFeatureListMember" abstract="true"
      eSuperTypes="#//Member">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" unique="false"
        upperBound="-1" eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiresMember" eSuperTypes="#//AbstractFeatureListMember"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidesMember" eSuperTypes="#//AbstractFeatureListMember"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFileListMember" abstract="true"
      eSuperTypes="#//Member">
    <eStructuralFeatures xsi:type="ecore:EReference" name="files" upperBound="-1"
        eType="#//FileName" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceMember" eSuperTypes="#//AbstractFileListMember"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectMember" eSuperTypes="#//AbstractFileListMember"/>
  <eClassifiers xsi:type="ecore:EClass" name="FileName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OptionMember" eSuperTypes="#//Member">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="#//Property"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//Named #//AnnotationTarget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringProperty" eSuperTypes="#//Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumberProperty" eSuperTypes="#//Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanProperty" eSuperTypes="#//Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="TypeProperty" eSuperTypes="#//Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="Value">
    <eOperations name="toString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberLiteral" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanLiteral" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isTrue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeLiteral" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyValueBinding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Value"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Named">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
