#!/bin/bash

QEMU=qemu-system-i386
#IMAGE=../../embox-nat1
IMAGE=../../build/base/bin/embox

cd "$(dirname "$0")"

sudo $QEMU -kernel $IMAGE \
 -net nic,model=e1000,macaddr=AA:BB:CC:DD:EE:11 \
 -net socket,mcast=230.0.0.1:12345 -nographic $@
