/*
* generated by Xtext
*/
package org.mybuild.myfile.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class MyFileOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
