$_APIS += embox.hal.bluetooth_drv

$_MODS += nxt_bluetooth
$_SRCS-nxt_bluetooth += nxt_bluetooth_usart.c nxt_bluetooth_assist.c
$_DEPS-nxt_bluetooth += embox.driver.pins
$_PROVIDES-nxt_bluetooth += embox.hal.bluetooth_drv
