/*
 * generated by Xtext
 */
package org.embuild.emdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EmDslRuntimeModule extends org.embuild.emdsl.AbstractEmDslRuntimeModule {

}
