/*
 * generated by Xtext
 */
package org.mybuild.myfile;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyFileRuntimeModule extends org.mybuild.myfile.AbstractMyFileRuntimeModule {

}
