/*
 * generated by Xtext
 */
package org.mybuild.myfile;

import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.scoping.IScopeProvider;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.mybuild.myfile.naming.MyQualifiedNameProvider;
import org.mybuild.myfile.scoping.MyImportedNamespaceAwareLocalScopeProvider;

import static com.google.inject.name.Names.named;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class MyFileRuntimeModule extends
		org.mybuild.myfile.AbstractMyFileRuntimeModule {

	@Override
	public void configureIScopeProviderDelegate(com.google.inject.Binder binder) {
		binder.bind(IScopeProvider.class)
				.annotatedWith(
						named(AbstractDeclarativeScopeProvider.NAMED_DELEGATE))
				.to(MyImportedNamespaceAwareLocalScopeProvider.class);
	}

	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return MyQualifiedNameProvider.class;
	}

}
