<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="emDsl"
    nsURI="http://www.embuild.org/emdsl/EmDsl" nsPrefix="emDsl">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.embuild.emdsl/src-gen/org/embuild/emdsl/EmDsl.ecore#//Entity"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Modifier" eSuperTypes="platform:/resource/org.embuild.emdsl/src-gen/org/embuild/emdsl/EmDsl.ecore#//Module">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module" eSuperTypes="platform:/resource/org.embuild.emdsl/src-gen/org/embuild/emdsl/EmDsl.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="ecore:EClass platform:/resource/org.embuild.emdsl/src-gen/org/embuild/emdsl/EmDsl.ecore#//Module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.embuild.emdsl/src-gen/org/embuild/emdsl/EmDsl.ecore#//Feature"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature"/>
  <eClassifiers xsi:type="ecore:EClass" name="SourceFeature" eSuperTypes="platform:/resource/org.embuild.emdsl/src-gen/org/embuild/emdsl/EmDsl.ecore#//Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filenames" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependFeature" eSuperTypes="platform:/resource/org.embuild.emdsl/src-gen/org/embuild/emdsl/EmDsl.ecore#//Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" unique="false"
        upperBound="-1" eType="ecore:EClass platform:/resource/org.embuild.emdsl/src-gen/org/embuild/emdsl/EmDsl.ecore#//Module"/>
  </eClassifiers>
</ecore:EPackage>
