$_MODS += box_around

$_SRCS-box_around += box_around.c

$_DEPS-box_around += $(PLATFORM).driver.sonar_sensor
$_DEPS-box_around += $(PLATFORM).driver.nxt_motor
$_DEPS-box_around += $(PLATFORM).driver.nxt_avr_init
