/*
 * generated by Xtext
 */
package org.mybuild.configfile.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;
import org.mybuild.myfile.ui.syntaxcoloring.MyFileHighlightingConfiguration;
import org.mybuild.myfile.ui.syntaxcoloring.MyFileSemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ConfigFileUiModule extends org.mybuild.configfile.ui.AbstractConfigFileUiModule {
	public ConfigFileUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
		return MyFileSemanticHighlightingCalculator.class;
	}

	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return MyFileHighlightingConfiguration.class;
	}

}
