root_dir = '.'
build_dir = 'build'

import sys

sys.path.insert(0, './tools')


def init(ctx):
    ctx.load('mywaf')


def options(ctx):
    ctx.load('mywaf')

    ctx.add_option('--template', type='string', default='', action='store',
                   help='using template')


def configure(ctx):
    ctx.load('mywaf')

    template_path = 'templates/' + ctx.options.template
    sys.path.insert(0, template_path)
    import build

    crosstool = getattr(build, 'CROSS_COMPILE', '')
    ctx.env.CC = crosstool + "gcc"
    ctx.env.LD = crosstool + "ld"
    ctx.env.TEMPLATE = template_path

    for flag in ['CFLAGS', 'CXXFLAGS', 'CPPFLAGS', 'LDFLAGS', 'ARFLAGS', 'ASFLAGS']:
        setattr(ctx.env, 'user_' + flag, getattr(build, flag, []))

    ctx.find_program(ctx.env.CC, var='CC')
    ctx.find_program(ctx.env.LD, var='LD')


def build(bld):
    bld.load('mywaf')

    # print(bld.env.TEMPLATE + '/conf.py')
    conf = bld.mybuild('prj.conf.conf', path=['src', bld.env.TEMPLATE])

    print(conf)

