root_dir = '.'
build_dir = 'build'

import os
import sys

sys.path.insert(0, './tools')
import mybuild.mywaf


def options(ctx):
    ctx.add_option('--template', type='string', default='', action='store',
                   help='using template')


def configure(ctx):
    template_path = 'templates/' + ctx.options.template
    sys.path.insert(0, template_path)
    import build

    crosstool = getattr(build, 'CROSS_COMPILE', '')
    ctx.env.CC = crosstool + "gcc"
    ctx.env.LD = crosstool + "ld"
    ctx.env.TEMPLATE = template_path

    for flag in ['CFLAGS', 'CXXFLAGS', 'CPPFLAGS', 'LDFLAGS', 'ARFLAGS', 'ASFLAGS']:
        setattr(ctx.env, 'user_' + flag, getattr(build, flag, []))
        #setattr(ctx.env, 'system_' + flag, getattr(mybuild.pybuild.flags, flag, []))
        #setattr(ctx.env, flag, getattr(ctx.env, 'system_' + flag) +
        #getattr(ctx.env, 'user_' + flag) +
        #getattr(ctx.env, flag))


    ctx.find_program(ctx.env.CC, var='CC')
    ctx.find_program(ctx.env.LD, var='LD')


def build(bld):
    print('CC ' + str(bld.env.CC))
    print('LD ' + str(bld.env.LD))
    print(bld.env.TEMPLATE + '/conf.py')

    sys.path.insert(0, './src')
    from prj import hello

    print hello.foo_mod

    # bld.load_myfiles('Mybuild')
    # bld.load_myfiles('conf.py', bld.path.find_node(bld.env.TEMPLATE))
