/*
 * generated by Xtext
 */
package org.mybuild.myfile.ui.outline;

import static org.mybuild.myfile.myFile.MyFilePackage.Literals.DEPENDS__MODULES;
import static org.mybuild.myfile.myFile.MyFilePackage.Literals.IMPORT__IMPORTED_NAMESPACE;
import static org.mybuild.myfile.myFile.MyFilePackage.Literals.MODEL__IMPORTS;
import static org.mybuild.myfile.myFile.MyFilePackage.Literals.PACKAGE__NAME;

import org.eclipse.emf.common.util.EList;
import org.eclipse.swt.graphics.Image;
import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.outline.impl.DocumentRootNode;
import org.mybuild.myfile.myFile.Depends;
import org.mybuild.myfile.myFile.Entity;
import org.mybuild.myfile.myFile.Filename;
import org.mybuild.myfile.myFile.FilenameAttribute;
import org.mybuild.myfile.myFile.Import;
import org.mybuild.myfile.myFile.Model;
import org.mybuild.myfile.myFile.Module;
import org.mybuild.myfile.myFile.Package;

/**
 * customization of the default outline structure
 * 
 */
public class MyFileOutlineTreeProvider extends DefaultOutlineTreeProvider {

	protected void _createChildren(DocumentRootNode parent, Model model) {
		Package pkg = model.getPackage();

		if (pkg != null) {
			createEStructuralFeatureNode(parent, pkg, PACKAGE__NAME,
					labelProvider.getImage(pkg), pkg.getName(), true);
		}

		EList<Import> imports = model.getImports();
		if (!imports.isEmpty()) {
			createEStructuralFeatureNode(parent, model, MODEL__IMPORTS,
					labelProvider.getImage(imports), "import declarations",
					false);
		}

		for (Entity entity : model.getEntities()) {
			createNode(parent, entity);
		}
	}

	protected void _createNode(IOutlineNode parent, Import imp) {
		createEStructuralFeatureNode(parent, imp, IMPORT__IMPORTED_NAMESPACE,
				labelProvider.getImage(imp), imp.getImportedNamespace(), true);
	}

	protected void _createNode(IOutlineNode parent, Depends depends) {
		Image image = labelProvider.getImage(depends);

		for (Module module : depends.getModules()) {
			String name = module.getName();
			if (name != null) {
				createEStructuralFeatureNode(parent, depends, DEPENDS__MODULES,
						image, name, true);
			}
		}
	}

	protected void _createNode(IOutlineNode parent,
			FilenameAttribute filenameAttribute) {
		for (Filename filename : filenameAttribute.getFiles()) {
			createNode(parent, filename);
		}
	}

}
