/*
 * generated by Xtext
 */
package org.mybuild.configfile.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ConfigFileUiModule extends org.mybuild.configfile.ui.AbstractConfigFileUiModule {
	public ConfigFileUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
