/*
 * generated by Xtext
 */
package org.mybuild.myfile.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.hyperlinking.IHyperlinkHelper;
import org.mybuild.myfile.ui.navigation.MyFileHyperlinkHelper;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyFileUiModule extends org.mybuild.myfile.ui.AbstractMyFileUiModule {
	public MyFileUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	@Override
	public Class<? extends IHyperlinkHelper> bindIHyperlinkHelper() {
		return MyFileHyperlinkHelper.class;
	}

}
