/*
 * generated by Xtext
 */
package org.mybuild.myfile.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyFileUiModule extends org.mybuild.myfile.ui.AbstractMyFileUiModule {
	public MyFileUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
