/*
* generated by Xtext
*/
package org.embuild.emdsl.ui.contentassist;

import org.embuild.emdsl.ui.contentassist.AbstractEmDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class EmDslProposalProvider extends AbstractEmDslProposalProvider {

}
